# Generated by Django 4.2.1 on 2023-05-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('dev_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dev_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percentage_used', models.FloatField(max_length=5)),
                ('memory_percentage_used', models.FloatField(max_length=5)),
                ('harddisk_percentage_used', models.FloatField(max_length=5)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_manufacturer', models.CharField(max_length=60)),
                ('dev_model', models.CharField(max_length=60)),
                ('dev_os', models.FloatField(max_length=5)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.generalinfo')),
            ],
        ),
    ]
