# Generated by Django 4.2.1 on 2023-05-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedinfo',
            options={'verbose_name': 'Advanced Info', 'verbose_name_plural': 'Advanced Infos'},
        ),
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name': 'General Info', 'verbose_name_plural': 'General Infos'},
        ),
        migrations.AlterModelOptions(
            name='performancemetrics',
            options={'verbose_name': 'Performance Metrics', 'verbose_name_plural': 'Performance Metrics'},
        ),
        migrations.AddField(
            model_name='advancedinfo',
            name='dev_snmp_port',
            field=models.IntegerField(default=161, verbose_name='SNMP Port'),
        ),
        migrations.AddField(
            model_name='advancedinfo',
            name='dev_ssh_port',
            field=models.IntegerField(default=22, verbose_name='SSH Port'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='dev_ip_address',
            field=models.CharField(blank=True, help_text="IP address in the format '192.168.1.1'", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='dev_manufacturer',
            field=models.CharField(max_length=60, verbose_name='Device Manufacturer'),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='dev_model',
            field=models.CharField(max_length=60, verbose_name='Device Model'),
        ),
        migrations.AlterField(
            model_name='advancedinfo',
            name='dev_os',
            field=models.CharField(max_length=60, verbose_name='Device OS'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='dev_name',
            field=models.CharField(max_length=60, verbose_name='Device Name'),
        ),
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_status', models.IntegerField(default=-1, verbose_name='Device Status')),
                ('dev_ping_status', models.BooleanField(verbose_name='Device Ping Status')),
                ('dev_ssh_status', models.BooleanField(verbose_name='Device SSH Status')),
                ('dev_snmp_status', models.BooleanField(verbose_name='Device SNMP Status')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.generalinfo')),
            ],
            options={
                'verbose_name': 'Status Info',
                'verbose_name_plural': 'Status Infos',
            },
        ),
    ]
