# Generated by Django 4.2.1 on 2023-05-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_advancedinfo_options_alter_generalinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percentage_used', models.FloatField(max_length=5)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.generalinfo')),
            ],
        ),
    ]
