# Generated by Django 4.2.1 on 2023-05-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cpu_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu_history',
            options={'verbose_name': 'CPU History', 'verbose_name_plural': 'CPU History'},
        ),
    ]
