# Generated by Django 4.2.1 on 2023-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_cpu_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_history',
            name='dev_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
