# Generated by Django 4.2.1 on 2023-05-29 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cpu_history_dev_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_history',
            name='dev_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
