# Generated by Django 4.2.1 on 2023-05-29 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_cpu_history_dev_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu_history',
            name='dev_datetime',
        ),
        migrations.AddField(
            model_name='cpu_history',
            name='dev_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cpu_history',
            name='dev_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
